### ISSUE TITLE
Add Javascript to make Nav sticky

### ISSUE THREAD

**Issue by AlexandraOM** [fac18/screaming-bear-solutions#4]
On scroll down we want our nav bar to disappear, but reappear as soon as you start to scroll back up.
On mobile the nav bar will be a logo and (if content too large) a hamburger menu.

As a client looking to hire a team of developers

> I want to visit your site and see a navigation link for 'About, Team, and Contact'

> so I can quickly navigate to the areas of the site I'd like to visit.

**Comment by kin-au** [comment]
Done, using CSS, see issue #15
