### ISSUE TITLE
Use a .gitignore

### ISSUE THREAD

**Issue by arrested-developer** [fac18/screaming-bear-solutions#42]
You can choose a gitignore when you first set up a repo on Github. You have committed .DS_Store files, which won't cause any problems for your project, but are system files from Mac OS that are not part of your codebase, so don't belong in your repo.

As you've already committed the .DS_Store files, you'll need to first delete them (you can use git rm to do this) and then make a commit so that they're no longer part of your git repo. Then you can add a gitignore file to prevent them being committed again.

**Comment by sleepysnapdragon** [comment]
after some git missteps, this is done!!
