### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by arrested-developer** [fac18/screaming-bear-solutions#43]
https://github.com/fac18/screaming-bear-solutions/blob/4b9e3b3c3d4d3bb8f44d3f4924afad1972710bd4/index.html#L34-L59

What the flip is going on with this indentation? Most of your HTML is nicely indented. You can agree as a team how much indentation to use for nested elements (a tab? 2 spaces? 4 spaces?) and configure your code editor so that your tab key provides the necessary spacing.

**Comment by ReginaldJbeili** [comment]
indentation fixed, added <p> tags and removed <br> tags
