### ISSUE TITLE
Write imperative commits

### ISSUE THREAD

**Issue by arrested-developer** [fac18/screaming-bear-solutions#45]
You might notice that when Git writes its own commit messages it uses the imperative form of the verb, e.g.

`merge branch master into current`

rather than something like

`merges the master branch`

It's widely accepted as best practice to write your commit messages in this way too, e.g. `fix`, not `fixed` or `fixes`.

[This article](https://chris.beams.io/posts/git-commit/) explains much better than I just tried to

**Comment by reubengt** [comment]
### A screenshot from the article that explains this convention and makes it easier to remember 🌻 
<img width="688" alt="Screenshot 2019-10-31 at 21 32 17" src="https://user-images.githubusercontent.com/42008435/67987711-025b3780-fc26-11e9-96dc-42a6851e8643.png">

**Comment by ReginaldJbeili** [comment]
Noted and thank you.
