### ISSUE TITLE
Commits and Contributions

### ISSUE THREAD

**Issue by gminova** [fac18/screaming-bear-solutions#50]
Your commits and contributions per member seem to range quite a bit with 14 being the highest and only 4 for the lowest. Be mindful to switch pairs more regularly rather than working on one machine. Also, remember to keep committing regularly. :)

![Screenshot from 2019-11-01 10-31-10](https://user-images.githubusercontent.com/42014388/68019119-d3c77600-fc92-11e9-8b38-1d55682bf894.png)
![Screenshot from 2019-11-01 10-31-21](https://user-images.githubusercontent.com/42014388/68019120-d3c77600-fc92-11e9-9a35-0449e41e6ca5.png)

**Comment by ReginaldJbeili** [comment]
Noted and thank you.
