### ISSUE TITLE
Uppercasing words

### ISSUE THREAD

**Issue by bobbysebolao** [fac18/screaming-bear-solutions#60]
Some of the tags in index.html contain capitalised text. You might find that a screen-reader will read these words letter by letter as though they were acronyms.

One of the other team's projects uses a more different method for uppercasing words that avoids this issue. Maybe ask around the room, or have a Google to find out how!

**Comment by sleepysnapdragon** [comment]
We've looked into this but haven't found a solution yet!  We saw that team Dynamyk have used a capital only font (Montserrat Subrayada) in their project which is possible what you're alluding to?  Or from Google, it seemed like Aria Labels could be a way to manage the problem.  More research needed!
